Déposer une œuvre numérisée
	Description : Un membre a numérisé une œuvre et souhaite la partager avec la bibliothèque pour enrichir son fond.
	Acteurs : Membre authentifié
	Prérequis : Le membre est authentifié sur l’application par FranceConnect
	Étapes :
    1. Le membre authentifié demande à l’application à partager une œuvre.
    2. L’application affiche un formulaire de saisie d’information concernant l’œuvre.
    3. Le membre authentifié saisit les informations, et joint le fichier de l’œuvre numérisée.
    4. L’application demande confirmation de l’envoi.
    5. Le membre authentifié confirme l’envoi.
    6. L’application enregistre le  fichier dans le répertoire « à modérer ».
    7. L’application créer un numéro de transaction et l’enregistre dans le fichier journal local.
    8. L’application transmet le fichier, ses informations et les numéros de transaction au dépôt sur le serveur de l’association.
    9. Les serveurs de l’association notifient les bibliothécaires qu’une nouvelle œuvre est en attente de modération.
    10. L’application indique au membre que son partage est en attente de modération.
	Scénarios alternatifs :
	Scénarios erreurs :
		Erreur de connexion avec le serveur.
	Données, documents, écrans :
@startuml
actor Member
participant uim_UIManager as UIM
participant FileShareForm as Form
Membre -> Application : Partager œuvre
Application -> UIM : getFileShareForm()
create Form
UIM -> Form :show()
Member -> Form : see
Application -> Membre : Afficher formulaire
Membre -> Form : fill(content_name, content_type, file)
Membre -> Form : Ajouter fichier
Membre -> Application : Envoyer formulaire
Application -> Application : Analyse fichier
Application -> Membre : Afficher résultat analyse fichier
Application -> Membre : Demander confirmation envoi
Membre -> Application : Valider envoi
Application -> Application : Copier fichier dans répertoire "À modérer"
Application -> Application : Créer numéro transaction
Application -> Application : Enregistrer transaction dans fichier de log
Application -> Form
destroy Form
Application -> Serveur : Transmettre transaction et fichier 
Serveur -> Bibliothécaire : Notifier de la soumission d'une œuvre
Application -> Membre : Notifier de l'attente de modération
@enduml